### ISSUE TITLE
Failed: A record with those settings already exists.

### ISSUE THREAD

**Issue by TheHett** [DrMegahertz/ansible-cloudflare#1]
Hi, 
in use i found problem with a round robin:

![image](https://cloud.githubusercontent.com/assets/946246/7696567/55ead5a8-fe20-11e4-9f65-2c950fcf5bad.png)
```
- cloudflare_domain: >
    state=present
    name=ftp
    zone=my_zone
    type=A
    content={{ external_ip_1 }}
    email=secret
    token=secret
```

It given error:

```
failed: [server_name] => {"failed": true}
msg: A record with those settings already exists.

FATAL: all hosts have already failed -- aborting
```

expected 
```
ok: [server_name]
```
or 
```
changed: [server_name]
```

UPD:
When i absent record, it must be remove one record with the specified name and content, but now plugin remove all records for specified name (domain)

**Comment by TheHett** [comment]
```
record = filter(lambda x: x['name'] == name, existing_records)
```
Hm, at least still required additional filtering by record content,
I don't know Python

**Comment by DrMegahertz** [comment]
I've got a commit ready that I'll push later today.

Thank you for reporting the issue! :)

**Comment by TheHett** [comment]
Thanks! :+1:

**Comment by TheHett** [comment]
Could you release 0.2.1 ?

**Comment by DrMegahertz** [comment]
No problem!

I've pushed it to master for now, and I'll try to make a proper release this evening.

Cheers.

**Comment by DrMegahertz** [comment]
0.3.0 is available at the Ansible Galaxy.

**Comment by TheHett** [comment]
@DrMegahertz Thank you!

**Comment by DrMegahertz** [comment]
You're welcome! :)
