### ISSUE TITLE
Removing multiple records

### ISSUE THREAD

**Issue by jugglinmike** [DrMegahertz/ansible-cloudflare#7]
I am writing a play that operates on a publically-accessible server, moving it behind a reverse proxy. This module works perfectly for creating a new record for the reverse proxy, but the difficult part is removing previously-existing entries. [As written, the module will only remove a single record if its
`name`, `type`, and `content` match some specific set of values.](https://github.com/DrMegahertz/ansible-cloudflare/blob/76e738959a6f91eaccd0ecd0c749f85780031d74/library/cloudflare_domain.py#L131) For this use case, I would like to remove *all* records (zero or more) according to `name` and `type` only.

Would this feature be considered for inclusion in the upstream project? If so, I'd be happy to implement it in whatever way the maintainers prefer. Some possibilities:

- Making `content` optional when `state` is set to "present", and implicitly removing all records that satisfy the criteria in that case
- Adding new configuration to explicitly opt in to this behavior
  - a new value for the `state` option such as "removeall"
  - a new option like `many` that may be set to True
- Special-casing the value of the `content` option--if set to "\*", then match anything.

I'm partial to the last option, but there's probably others that I'm not considering. Anyway, would this feature be considered for inclusion here?

**Comment by jugglinmike** [comment]
Actually, it looks like Cloudflare already special-cases the "*" value as a wildcard. This means that `content: *` could actually describe a specific record, so that approach is out. Maybe `content: null`...?

**Comment by jugglinmike** [comment]
Or a regular expression. That would address my use case in an explicit way (`content: /.*/`), and possibly allow for even greater flexibility. This value would be specified as a string, but this module can unambiguously differentiate between literal values and patterns because valid DNS entries can't include a forward slash (`/`) character. This is probably over-engineering it, though.

**Comment by DrMegahertz** [comment]
I can't seem to find anything about a content-value of '*' in the API docs? But I would expect the following behaviour:

Let's assume that we have the following records:

    db.example.com A 127.0.0.1
    www.example.com A 127.0.0.2
    www.example.com A 127.0.0.3

I'd like to remove both of the www.example.com-records, so I'd call the module with the following parameters:

    cloudflare_domain: >
      state=absent
      name=www
      zone=example.com
      content=*

Now I'd expect our zone-file to just contain:

    db.example.com A 127.0.0.1

Do cloudflare treat the '*' differently from what I expect?

**Comment by DrMegahertz** [comment]
Agreed, regexes does sound like overkill.

**Comment by jugglinmike** [comment]
I think it does. From https://support.cloudflare.com/hc/en-us/articles/200168826:

> CloudFlare supports the wildcard * record for DNS management at all plan types. For CloudFlare Enterprise customers, we offer full proxy support for wildcard records.

Shame, because I think using the star as you've demonstrated in that example is the most elegant option

**Comment by DrMegahertz** [comment]
Ah, but the wildcard would go in the name parameter in that case, as such:

    cloudflare_domain: >
      name=*
      zone=example.com
      type=A
      content=127.0.0.1

This would leave us with the following record:

    *.example.com A 127.0.0.1

See https://en.wikipedia.org/wiki/Wildcard_DNS_record .

Unless I'm being tired and misunderstood something?

**Comment by jugglinmike** [comment]
Nope, you are completely correct. That's great!

**Comment by DrMegahertz** [comment]
In that case I'm all in favour of merging a branch that implements your last suggestion. :)
